/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

import javax.swing.JOptionPane;

/**
 *
 * @author u08059751107
 */
public class JDlgElzVendedor extends javax.swing.JDialog {

    /**
     * Creates new form Vendedor
     */
    public JDlgElzVendedor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastro de Vendedor");
        setLocationRelativeTo(null);
        habilitar(false);
    }
    public void habilitar(boolean valor) {
       jTxtElzNome.setEnabled(valor);
       jChbElzAtivo.setEnabled(valor);
       jFmtElzCpf.setEnabled(valor);
       jFmtElzEmail.setEnabled(valor);
       jTxtElzCodigo.setEnabled(valor);
       jFmtElzDataCadastro.setEnabled(valor);
       jFmtElzTelefone.setEnabled(valor);
       jBtnElzConfirmar.setEnabled(valor);
       jBtnElzCancelat.setEnabled(valor);
       jBtnElzAlterar.setEnabled(!valor);
       jBtnElzExcluir.setEnabled(!valor);
       jBtnElzIncluir.setEnabled(!valor);
       jBtnElzPesquisar.setEnabled(!valor);
       
    }  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnElzExcluir = new javax.swing.JButton();
        jBtnElzCancelat = new javax.swing.JButton();
        jLblElzDataCadastro = new javax.swing.JLabel();
        jBtnElzConfirmar = new javax.swing.JButton();
        jBtnElzPesquisar = new javax.swing.JButton();
        jLblElzTelefone = new javax.swing.JLabel();
        jLblElzNome = new javax.swing.JLabel();
        jLblElzCodigo = new javax.swing.JLabel();
        jLblElzEmail = new javax.swing.JLabel();
        jTxtElzCodigo = new javax.swing.JTextField();
        jTxtElzNome = new javax.swing.JTextField();
        jChbElzAtivo = new javax.swing.JCheckBox();
        jFmtElzCpf = new javax.swing.JFormattedTextField();
        jBtnElzIncluir = new javax.swing.JButton();
        jLblCpf = new javax.swing.JLabel();
        jBtnElzAlterar = new javax.swing.JButton();
        jFmtElzTelefone = new javax.swing.JFormattedTextField();
        jFmtElzDataCadastro = new javax.swing.JFormattedTextField();
        jFmtElzEmail = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jBtnElzExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir.png"))); // NOI18N
        jBtnElzExcluir.setText("Excluir");
        jBtnElzExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnElzExcluirActionPerformed(evt);
            }
        });

        jBtnElzCancelat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jBtnElzCancelat.setText("Cancelar");
        jBtnElzCancelat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnElzCancelatActionPerformed(evt);
            }
        });

        jLblElzDataCadastro.setText("Data Cadastro");

        jBtnElzConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/confirmar.jpg"))); // NOI18N
        jBtnElzConfirmar.setText("Confirmar");
        jBtnElzConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnElzConfirmarActionPerformed(evt);
            }
        });

        jBtnElzPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jBtnElzPesquisar.setText("Pesquisar");
        jBtnElzPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnElzPesquisarActionPerformed(evt);
            }
        });

        jLblElzTelefone.setText("Telefone");

        jLblElzNome.setText("Nome");

        jLblElzCodigo.setText("Codigo");

        jLblElzEmail.setText("Email");

        jChbElzAtivo.setText("ativo");

        jBtnElzIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        jBtnElzIncluir.setText("Incluir");
        jBtnElzIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnElzIncluirActionPerformed(evt);
            }
        });

        jLblCpf.setText("CPF");

        jBtnElzAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jBtnElzAlterar.setText("Alterar");
        jBtnElzAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnElzAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLblElzNome)
                                    .addComponent(jLblElzCodigo))
                                .addGap(360, 663, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLblElzDataCadastro)
                                    .addComponent(jFmtElzDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jFmtElzTelefone)
                                        .addGap(34, 34, 34)
                                        .addComponent(jChbElzAtivo)
                                        .addGap(43, 43, 43))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLblElzTelefone)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtElzNome, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtElzCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFmtElzCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLblCpf))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLblElzEmail)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jFmtElzEmail)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBtnElzIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnElzAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnElzExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnElzCancelat)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnElzConfirmar)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnElzPesquisar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLblElzCodigo)
                .addGap(12, 12, 12)
                .addComponent(jTxtElzCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLblElzNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtElzNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblCpf)
                    .addComponent(jLblElzEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFmtElzCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtElzEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLblElzDataCadastro)
                            .addComponent(jLblElzTelefone))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFmtElzTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFmtElzDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtnElzConfirmar)
                            .addComponent(jBtnElzCancelat)
                            .addComponent(jBtnElzExcluir)
                            .addComponent(jBtnElzAlterar)
                            .addComponent(jBtnElzIncluir)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jChbElzAtivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnElzPesquisar)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnElzConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnElzConfirmarActionPerformed
         habilitar(false);  
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnElzConfirmarActionPerformed

    private void jBtnElzIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnElzIncluirActionPerformed
        habilitar(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnElzIncluirActionPerformed

    private void jBtnElzAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnElzAlterarActionPerformed
        habilitar(true);
// TODO add your handling code here:
    }//GEN-LAST:event_jBtnElzAlterarActionPerformed

    private void jBtnElzExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnElzExcluirActionPerformed
         JOptionPane.showConfirmDialog(null, "A exclusão não poderá ser desfeita. Deseja continuar?",
"Excluir registro", JOptionPane.YES_NO_OPTION);
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnElzExcluirActionPerformed

    private void jBtnElzCancelatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnElzCancelatActionPerformed
          habilitar(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnElzCancelatActionPerformed

    private void jBtnElzPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnElzPesquisarActionPerformed
       JOptionPane.showInputDialog(null, "Informe o código do Cliente:");
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnElzPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgElzVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgElzVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgElzVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgElzVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgElzVendedor dialog = new JDlgElzVendedor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnElzAlterar;
    private javax.swing.JButton jBtnElzCancelat;
    private javax.swing.JButton jBtnElzConfirmar;
    private javax.swing.JButton jBtnElzExcluir;
    private javax.swing.JButton jBtnElzIncluir;
    private javax.swing.JButton jBtnElzPesquisar;
    private javax.swing.JCheckBox jChbElzAtivo;
    private javax.swing.JFormattedTextField jFmtElzCpf;
    private javax.swing.JFormattedTextField jFmtElzDataCadastro;
    private javax.swing.JFormattedTextField jFmtElzEmail;
    private javax.swing.JFormattedTextField jFmtElzTelefone;
    private javax.swing.JLabel jLblCpf;
    private javax.swing.JLabel jLblElzCodigo;
    private javax.swing.JLabel jLblElzDataCadastro;
    private javax.swing.JLabel jLblElzEmail;
    private javax.swing.JLabel jLblElzNome;
    private javax.swing.JLabel jLblElzTelefone;
    private javax.swing.JTextField jTxtElzCodigo;
    private javax.swing.JTextField jTxtElzNome;
    // End of variables declaration//GEN-END:variables
}
