/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

import javax.swing.JOptionPane;

/**
 *
 * @author u08059751107
 */
public class JDlgElzProduto extends javax.swing.JDialog {

    /**
     * Creates new form JDlgElzProduto
     */
    public JDlgElzProduto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastro de Produto");
        setLocationRelativeTo(null);
        habilitar(false);
    }
          public void habilitar(boolean valor) {
       jTxtElzNome.setEnabled(valor);
       jFmtElzDataNascimento.setEnabled(valor);
       jTxtElzDescricao.setEnabled(valor);
       jFmtElzMarca.setEnabled(valor);
       jFmtElzCodigoDeBarra.setEnabled(valor);
       jTxtElzCodigo.setEnabled(valor);
       jChbElzAtivo.setEnabled(valor);
       jPwfElzSenha.setEnabled(valor);
       jBtnElzConfirmar.setEnabled(valor);
       jBtnElzCancelat.setEnabled(valor);
       jBtnElzAlterar.setEnabled(!valor);
       jBtnElzExcluir.setEnabled(!valor);
       jBtnElzIncluir.setEnabled(!valor);
       jBtnElzPesquisar.setEnabled(!valor);
    } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblElzPreco = new javax.swing.JLabel();
        jBtnElzExcluir = new javax.swing.JButton();
        jFmtElzDataNascimento = new javax.swing.JFormattedTextField();
        jBtnElzCancelat = new javax.swing.JButton();
        jLblElzCategoria = new javax.swing.JLabel();
        jBtnElzConfirmar = new javax.swing.JButton();
        jPwfElzSenha = new javax.swing.JPasswordField();
        jBtnElzPesquisar = new javax.swing.JButton();
        jLblElzCodigoDeBarras = new javax.swing.JLabel();
        jLblElzNome = new javax.swing.JLabel();
        jLblElzCodigo = new javax.swing.JLabel();
        jLblElzApelido = new javax.swing.JLabel();
        jTxtElzCodigo = new javax.swing.JTextField();
        jTxtElzNome = new javax.swing.JTextField();
        jTxtElzDescricao = new javax.swing.JTextField();
        jChbElzAtivo = new javax.swing.JCheckBox();
        jFmtElzMarca = new javax.swing.JFormattedTextField();
        jBtnElzIncluir = new javax.swing.JButton();
        jLblCpf = new javax.swing.JLabel();
        jBtnElzAlterar = new javax.swing.JButton();
        jFmtElzCodigoDeBarra = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLblElzPreco.setText("Preço");

        jBtnElzExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir.png"))); // NOI18N
        jBtnElzExcluir.setText("Excluir");
        jBtnElzExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnElzExcluirActionPerformed(evt);
            }
        });

        jBtnElzCancelat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jBtnElzCancelat.setText("Cancelar");
        jBtnElzCancelat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnElzCancelatActionPerformed(evt);
            }
        });

        jLblElzCategoria.setText("Categoria");

        jBtnElzConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/check.png"))); // NOI18N
        jBtnElzConfirmar.setText("Confirmar");
        jBtnElzConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnElzConfirmarActionPerformed(evt);
            }
        });

        jBtnElzPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jBtnElzPesquisar.setText("Pesquisar");
        jBtnElzPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnElzPesquisarActionPerformed(evt);
            }
        });

        jLblElzCodigoDeBarras.setText("Codigo de barras");

        jLblElzNome.setText("Nome");

        jLblElzCodigo.setText("Codigo");

        jLblElzApelido.setText("Descrição");

        jChbElzAtivo.setText("ativo");

        jBtnElzIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        jBtnElzIncluir.setText("Incluir");
        jBtnElzIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnElzIncluirActionPerformed(evt);
            }
        });

        jLblCpf.setText("Marca");

        jBtnElzAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jBtnElzAlterar.setText("Alterar");
        jBtnElzAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnElzAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtElzCodigo)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtElzNome, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLblCpf)
                                    .addComponent(jLblElzCodigo)
                                    .addComponent(jLblElzCategoria)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jPwfElzSenha, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jFmtElzMarca, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jFmtElzCodigoDeBarra)
                                    .addComponent(jLblElzPreco, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFmtElzDataNascimento, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                    .addComponent(jLblElzCodigoDeBarras, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jChbElzAtivo)
                                .addGap(145, 145, 145))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLblElzNome)
                                .addGap(234, 234, 234)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLblElzApelido)
                                        .addGap(205, 205, 205))
                                    .addComponent(jTxtElzDescricao)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBtnElzIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnElzAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnElzExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnElzCancelat)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnElzConfirmar)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnElzPesquisar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLblElzCodigo)
                .addGap(12, 12, 12)
                .addComponent(jTxtElzCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLblElzNome)
                            .addComponent(jLblElzApelido))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtElzNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtElzDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLblCpf)
                            .addComponent(jLblElzPreco))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFmtElzMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFmtElzDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLblElzCategoria)
                            .addComponent(jLblElzCodigoDeBarras))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jPwfElzSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFmtElzCodigoDeBarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jBtnElzConfirmar)
                                    .addComponent(jBtnElzCancelat)
                                    .addComponent(jBtnElzExcluir)
                                    .addComponent(jBtnElzAlterar)
                                    .addComponent(jBtnElzIncluir)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jChbElzAtivo)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBtnElzPesquisar)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnElzConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnElzConfirmarActionPerformed
         habilitar(false);
// TODO add your handling code here:
    }//GEN-LAST:event_jBtnElzConfirmarActionPerformed

    private void jBtnElzIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnElzIncluirActionPerformed
        habilitar(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnElzIncluirActionPerformed

    private void jBtnElzAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnElzAlterarActionPerformed
         habilitar(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnElzAlterarActionPerformed

    private void jBtnElzExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnElzExcluirActionPerformed
         JOptionPane.showConfirmDialog(null, "A exclusão não poderá ser desfeita. Deseja continuar?",
"Excluir registro", JOptionPane.YES_NO_OPTION);
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnElzExcluirActionPerformed

    private void jBtnElzCancelatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnElzCancelatActionPerformed
         habilitar(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnElzCancelatActionPerformed

    private void jBtnElzPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnElzPesquisarActionPerformed
         JOptionPane.showConfirmDialog(null, "A exclusão não poderá ser desfeita. Deseja continuar?",
"Excluir registro", JOptionPane.YES_NO_OPTION);
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnElzPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgElzProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgElzProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgElzProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgElzProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgElzProduto dialog = new JDlgElzProduto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnElzAlterar;
    private javax.swing.JButton jBtnElzCancelat;
    private javax.swing.JButton jBtnElzConfirmar;
    private javax.swing.JButton jBtnElzExcluir;
    private javax.swing.JButton jBtnElzIncluir;
    private javax.swing.JButton jBtnElzPesquisar;
    private javax.swing.JCheckBox jChbElzAtivo;
    private javax.swing.JFormattedTextField jFmtElzCodigoDeBarra;
    private javax.swing.JFormattedTextField jFmtElzDataNascimento;
    private javax.swing.JFormattedTextField jFmtElzMarca;
    private javax.swing.JLabel jLblCpf;
    private javax.swing.JLabel jLblElzApelido;
    private javax.swing.JLabel jLblElzCategoria;
    private javax.swing.JLabel jLblElzCodigo;
    private javax.swing.JLabel jLblElzCodigoDeBarras;
    private javax.swing.JLabel jLblElzNome;
    private javax.swing.JLabel jLblElzPreco;
    private javax.swing.JPasswordField jPwfElzSenha;
    private javax.swing.JTextField jTxtElzCodigo;
    private javax.swing.JTextField jTxtElzDescricao;
    private javax.swing.JTextField jTxtElzNome;
    // End of variables declaration//GEN-END:variables
}
