/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

import javax.swing.JOptionPane;

/**
 *
 * @author u08059751107
 */
public class JDlgElzClientes extends javax.swing.JDialog {

    /**
     * Creates new form JDlgElzClientes
     */
    public JDlgElzClientes(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
    setTitle("Cadastro de Cliente");
    setLocationRelativeTo(null);
    habilitar(false);
}

      public void habilitar(boolean valor) {
       jTxtElzNome.setEnabled(valor);
       jFmtElzCep.setEnabled(valor);
       jFmtElzRg.setEnabled(valor);
       jFmtElzDataCadastro.setEnabled(valor);
       jFmtElzDataNascimento.setEnabled(valor);
       jFmtElzCpf.setEnabled(valor);
       jFmtElzEmail.setEnabled(valor);
       jFmtElzTelefone.setEnabled(valor);
       jTxtElzCodigo.setEnabled(valor);
       jTxtElzCidade.setEnabled(valor);
       jTxtElzEndereco.setEnabled(valor);
       jTxtElzEstado.setEnabled(valor);
       jChbElzAtivo.setEnabled(valor);
       jPwfElzSenha.setEnabled(valor);
       jTxtElzEndereco.setEnabled(valor);
       jTxtElzBairro.setEnabled(valor);
       jBtnElzConfirmar.setEnabled(valor);
       jBtnElzCancelat.setEnabled(valor);
       jBtnElzAlterar.setEnabled(!valor);
       jBtnElzExcluir.setEnabled(!valor);
       jBtnElzIncluir.setEnabled(!valor);
       jBtnElzPesquisar.setEnabled(!valor);
       
    }  
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblElzNome = new javax.swing.JLabel();
        jLblElzCPF = new javax.swing.JLabel();
        jLblElzRg = new javax.swing.JLabel();
        jLblElzDataNascimento = new javax.swing.JLabel();
        jLblElzEmail = new javax.swing.JLabel();
        Label = new javax.swing.JLabel();
        jLblElzTelefone = new javax.swing.JLabel();
        jLblElzCep = new javax.swing.JLabel();
        jLblElzEndereço = new javax.swing.JLabel();
        jLblElzBairro = new javax.swing.JLabel();
        jLblElzCidade = new javax.swing.JLabel();
        jLblElzEstado = new javax.swing.JLabel();
        jLblElzDataCadastro = new javax.swing.JLabel();
        jPwfElzSenha = new javax.swing.JPasswordField();
        jFmtElzCpf = new javax.swing.JFormattedTextField();
        jFmtElzDataCadastro = new javax.swing.JFormattedTextField();
        jFmtElzDataNascimento = new javax.swing.JFormattedTextField();
        jTxtElzNome = new javax.swing.JTextField();
        jFmtElzRg = new javax.swing.JFormattedTextField();
        jFmtElzCep = new javax.swing.JFormattedTextField();
        jTxtElzCidade = new javax.swing.JTextField();
        jTxtElzBairro = new javax.swing.JTextField();
        jTxtElzEstado = new javax.swing.JTextField();
        jTxtElzEndereco = new javax.swing.JTextField();
        jChbElzAtivo = new javax.swing.JCheckBox();
        jFmtElzEmail = new javax.swing.JFormattedTextField();
        jFmtElzTelefone = new javax.swing.JFormattedTextField();
        jBtnElzIncluir = new javax.swing.JButton();
        jBtnElzAlterar = new javax.swing.JButton();
        jBtnElzExcluir = new javax.swing.JButton();
        jBtnElzCancelat = new javax.swing.JButton();
        jBtnElzConfirmar = new javax.swing.JButton();
        jBtnElzPesquisar = new javax.swing.JButton();
        jLblElzCodigo = new javax.swing.JLabel();
        jTxtElzCodigo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLblElzNome.setText("Nome");

        jLblElzCPF.setText("CPF");

        jLblElzRg.setText("RG");

        jLblElzDataNascimento.setText("Data Nascimento");

        jLblElzEmail.setText("Email");

        Label.setText("Senha");

        jLblElzTelefone.setText("Telefone");

        jLblElzCep.setText("CEP");

        jLblElzEndereço.setText("Endereço");

        jLblElzBairro.setText("Bairro");

        jLblElzCidade.setText("Cidade");

        jLblElzEstado.setText("Estado");

        jLblElzDataCadastro.setText("Data Cadastro");

        jTxtElzBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtElzBairroActionPerformed(evt);
            }
        });

        jChbElzAtivo.setText("ativo");

        jBtnElzIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        jBtnElzIncluir.setText("Incluir");
        jBtnElzIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnElzIncluirActionPerformed(evt);
            }
        });

        jBtnElzAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jBtnElzAlterar.setText("Alterar");
        jBtnElzAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnElzAlterarActionPerformed(evt);
            }
        });

        jBtnElzExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir.png"))); // NOI18N
        jBtnElzExcluir.setText("Excluir");
        jBtnElzExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnElzExcluirActionPerformed(evt);
            }
        });

        jBtnElzCancelat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jBtnElzCancelat.setText("Cancelar");
        jBtnElzCancelat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnElzCancelatActionPerformed(evt);
            }
        });

        jBtnElzConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/check.png"))); // NOI18N
        jBtnElzConfirmar.setText("Confirmar");
        jBtnElzConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnElzConfirmarActionPerformed(evt);
            }
        });

        jBtnElzPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jBtnElzPesquisar.setText("Pesquisar");
        jBtnElzPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnElzPesquisarActionPerformed(evt);
            }
        });

        jLblElzCodigo.setText("Codigo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLblElzDataNascimento)
                        .addGap(50, 50, 50)
                        .addComponent(jLblElzEmail))
                    .addComponent(jLblElzCodigo)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblElzCep)
                            .addComponent(jFmtElzCep, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLblElzEndereço)
                                .addGap(189, 189, 189)
                                .addComponent(jLblElzBairro)
                                .addGap(116, 116, 116)
                                .addComponent(jLblElzCidade))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTxtElzEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtElzBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtElzCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jFmtElzDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFmtElzEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label)
                            .addComponent(jPwfElzSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLblElzEstado)
                            .addComponent(jTxtElzEstado, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                            .addComponent(jBtnElzIncluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnElzAlterar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBtnElzExcluir)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnElzCancelat)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnElzConfirmar)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnElzPesquisar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLblElzDataCadastro)
                                    .addComponent(jFmtElzDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLblElzTelefone)
                                    .addComponent(jFmtElzTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jChbElzAtivo))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtElzNome, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLblElzNome))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblElzCPF)
                            .addComponent(jFmtElzCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblElzRg, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFmtElzRg, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jTxtElzCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLblElzCodigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtElzCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblElzNome)
                    .addComponent(jLblElzRg)
                    .addComponent(jLblElzCPF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTxtElzNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Label)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLblElzDataNascimento)
                                .addComponent(jLblElzEmail)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFmtElzDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPwfElzSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFmtElzEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLblElzEndereço)
                            .addComponent(jLblElzCep)
                            .addComponent(jLblElzBairro)
                            .addComponent(jLblElzCidade))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtElzEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtElzBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtElzCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFmtElzCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLblElzEstado)
                            .addComponent(jLblElzDataCadastro)
                            .addComponent(jLblElzTelefone))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtElzEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFmtElzDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jChbElzAtivo)
                            .addComponent(jFmtElzTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtnElzIncluir)
                            .addComponent(jBtnElzAlterar)
                            .addComponent(jBtnElzExcluir)
                            .addComponent(jBtnElzCancelat)
                            .addComponent(jBtnElzConfirmar)
                            .addComponent(jBtnElzPesquisar))
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFmtElzCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFmtElzRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtElzBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtElzBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtElzBairroActionPerformed

    private void jBtnElzIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnElzIncluirActionPerformed
        habilitar(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnElzIncluirActionPerformed

    private void jBtnElzAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnElzAlterarActionPerformed
        habilitar(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnElzAlterarActionPerformed

    private void jBtnElzExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnElzExcluirActionPerformed
         JOptionPane.showConfirmDialog(null, "A exclusão não poderá ser desfeita. Deseja continuar?",
"Excluir registro", JOptionPane.YES_NO_OPTION);
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnElzExcluirActionPerformed

    private void jBtnElzCancelatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnElzCancelatActionPerformed
          habilitar(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnElzCancelatActionPerformed

    private void jBtnElzPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnElzPesquisarActionPerformed
          JOptionPane.showInputDialog(null, "Informe o código do Cliente:");
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnElzPesquisarActionPerformed

    private void jBtnElzConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnElzConfirmarActionPerformed
          habilitar(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnElzConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgElzClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgElzClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgElzClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgElzClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgElzClientes dialog = new JDlgElzClientes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label;
    private javax.swing.JButton jBtnElzAlterar;
    private javax.swing.JButton jBtnElzCancelat;
    private javax.swing.JButton jBtnElzConfirmar;
    private javax.swing.JButton jBtnElzExcluir;
    private javax.swing.JButton jBtnElzIncluir;
    private javax.swing.JButton jBtnElzPesquisar;
    private javax.swing.JCheckBox jChbElzAtivo;
    private javax.swing.JFormattedTextField jFmtElzCep;
    private javax.swing.JFormattedTextField jFmtElzCpf;
    private javax.swing.JFormattedTextField jFmtElzDataCadastro;
    private javax.swing.JFormattedTextField jFmtElzDataNascimento;
    private javax.swing.JFormattedTextField jFmtElzEmail;
    private javax.swing.JFormattedTextField jFmtElzRg;
    private javax.swing.JFormattedTextField jFmtElzTelefone;
    private javax.swing.JLabel jLblElzBairro;
    private javax.swing.JLabel jLblElzCPF;
    private javax.swing.JLabel jLblElzCep;
    private javax.swing.JLabel jLblElzCidade;
    private javax.swing.JLabel jLblElzCodigo;
    private javax.swing.JLabel jLblElzDataCadastro;
    private javax.swing.JLabel jLblElzDataNascimento;
    private javax.swing.JLabel jLblElzEmail;
    private javax.swing.JLabel jLblElzEndereço;
    private javax.swing.JLabel jLblElzEstado;
    private javax.swing.JLabel jLblElzNome;
    private javax.swing.JLabel jLblElzRg;
    private javax.swing.JLabel jLblElzTelefone;
    private javax.swing.JPasswordField jPwfElzSenha;
    private javax.swing.JTextField jTxtElzBairro;
    private javax.swing.JTextField jTxtElzCidade;
    private javax.swing.JTextField jTxtElzCodigo;
    private javax.swing.JTextField jTxtElzEndereco;
    private javax.swing.JTextField jTxtElzEstado;
    private javax.swing.JTextField jTxtElzNome;
    // End of variables declaration//GEN-END:variables
}
