/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

/**
 *
 * @author u08059751107
 */
public class JDlgElzClientes extends javax.swing.JDialog {

    /**
     * Creates new form JDlgElzClientes
     */
    public JDlgElzClientes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblElzNome = new javax.swing.JLabel();
        jLblElzCPF = new javax.swing.JLabel();
        jLblElzRg = new javax.swing.JLabel();
        jLblElzDataNascimento = new javax.swing.JLabel();
        jLblElzEmail = new javax.swing.JLabel();
        jPwfElzSenha = new javax.swing.JLabel();
        jLblElzTelefone = new javax.swing.JLabel();
        jLblElzCep = new javax.swing.JLabel();
        jLblElzEndereço = new javax.swing.JLabel();
        jLblElzBairro = new javax.swing.JLabel();
        jLblElzCidade = new javax.swing.JLabel();
        jLblElzEstado = new javax.swing.JLabel();
        jLblElzDataCadastro = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jFmtElzCpf = new javax.swing.JFormattedTextField();
        jFmtElzDataCadastro = new javax.swing.JFormattedTextField();
        jFmtElzDataNascimento = new javax.swing.JFormattedTextField();
        jTxtElzNome = new javax.swing.JTextField();
        jFmtElzRg = new javax.swing.JFormattedTextField();
        jFmtElzCep = new javax.swing.JFormattedTextField();
        jTxtElzCidade = new javax.swing.JTextField();
        jTxtElzBairro = new javax.swing.JTextField();
        jTxtElzEstado = new javax.swing.JTextField();
        jTxtElzEndereco = new javax.swing.JTextField();
        jChbElzAtivo = new javax.swing.JCheckBox();
        jFmtElzEmail = new javax.swing.JFormattedTextField();
        jFmtElzTelefone = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLblElzNome.setText("Nome");

        jLblElzCPF.setText("CPF");

        jLblElzRg.setText("RG");

        jLblElzDataNascimento.setText("Data Nascimento");

        jLblElzEmail.setText("Email");

        jPwfElzSenha.setText("Senha");

        jLblElzTelefone.setText("Telefone");

        jLblElzCep.setText("CEP");

        jLblElzEndereço.setText("Endereço");

        jLblElzBairro.setText("Bairro");

        jLblElzCidade.setText("Cidade");

        jLblElzEstado.setText("Estado");

        jLblElzDataCadastro.setText("Data Cadastro");

        jTxtElzBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtElzBairroActionPerformed(evt);
            }
        });

        jChbElzAtivo.setText("ativo");

        jButton1.setText("jButton1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblElzEstado)
                            .addComponent(jTxtElzEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblElzDataCadastro)
                            .addComponent(jFmtElzDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblElzTelefone)
                            .addComponent(jFmtElzTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jChbElzAtivo))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblElzCep)
                            .addComponent(jFmtElzCep, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLblElzEndereço)
                                .addGap(189, 189, 189)
                                .addComponent(jLblElzBairro)
                                .addGap(116, 116, 116)
                                .addComponent(jLblElzCidade))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTxtElzEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtElzBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtElzCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLblElzDataNascimento)
                                .addGap(50, 50, 50)
                                .addComponent(jLblElzEmail)
                                .addGap(353, 353, 353))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTxtElzNome, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jFmtElzCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jFmtElzRg, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLblElzNome)
                            .addGap(324, 324, 324)
                            .addComponent(jLblElzCPF)
                            .addGap(169, 169, 169)
                            .addComponent(jLblElzRg, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(43, 43, 43))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jFmtElzDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jFmtElzEmail)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPwfElzSenha)
                                .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblElzCPF)
                    .addComponent(jLblElzNome)
                    .addComponent(jLblElzRg))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtElzNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtElzCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtElzRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPwfElzSenha)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLblElzDataNascimento)
                        .addComponent(jLblElzEmail)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFmtElzDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtElzEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblElzEndereço)
                    .addComponent(jLblElzCep)
                    .addComponent(jLblElzBairro)
                    .addComponent(jLblElzCidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtElzEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtElzBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtElzCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtElzCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblElzEstado)
                    .addComponent(jLblElzDataCadastro)
                    .addComponent(jLblElzTelefone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtElzEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtElzDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jChbElzAtivo)
                    .addComponent(jFmtElzTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtElzBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtElzBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtElzBairroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgElzClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgElzClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgElzClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgElzClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgElzClientes dialog = new JDlgElzClientes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jChbElzAtivo;
    private javax.swing.JFormattedTextField jFmtElzCep;
    private javax.swing.JFormattedTextField jFmtElzCpf;
    private javax.swing.JFormattedTextField jFmtElzDataCadastro;
    private javax.swing.JFormattedTextField jFmtElzDataNascimento;
    private javax.swing.JFormattedTextField jFmtElzEmail;
    private javax.swing.JFormattedTextField jFmtElzRg;
    private javax.swing.JFormattedTextField jFmtElzTelefone;
    private javax.swing.JLabel jLblElzBairro;
    private javax.swing.JLabel jLblElzCPF;
    private javax.swing.JLabel jLblElzCep;
    private javax.swing.JLabel jLblElzCidade;
    private javax.swing.JLabel jLblElzDataCadastro;
    private javax.swing.JLabel jLblElzDataNascimento;
    private javax.swing.JLabel jLblElzEmail;
    private javax.swing.JLabel jLblElzEndereço;
    private javax.swing.JLabel jLblElzEstado;
    private javax.swing.JLabel jLblElzNome;
    private javax.swing.JLabel jLblElzRg;
    private javax.swing.JLabel jLblElzTelefone;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel jPwfElzSenha;
    private javax.swing.JTextField jTxtElzBairro;
    private javax.swing.JTextField jTxtElzCidade;
    private javax.swing.JTextField jTxtElzEndereco;
    private javax.swing.JTextField jTxtElzEstado;
    private javax.swing.JTextField jTxtElzNome;
    // End of variables declaration//GEN-END:variables
}
