/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author u08059751107
 */
public class JFrmElzPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFrmElzPrincipal
     */
    public JFrmElzPrincipal() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jChbElzCadastro = new javax.swing.JMenu();
        jChbElzUsuarios = new javax.swing.JCheckBoxMenuItem();
        jChbElzClientes = new javax.swing.JCheckBoxMenuItem();
        jChbElzFornecedo = new javax.swing.JCheckBoxMenuItem();
        jChbElzProdutos = new javax.swing.JCheckBoxMenuItem();
        jChbElzVendedor = new javax.swing.JCheckBoxMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jChbElzSaie = new javax.swing.JCheckBoxMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jCheckBoxMenuItem4 = new javax.swing.JCheckBoxMenuItem();
        jChbElzVendaProduto = new javax.swing.JCheckBoxMenuItem();
        jChbElzCompras = new javax.swing.JCheckBoxMenuItem();
        jChbElzComprasProduto = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jChbElzCadastro.setText("Cadastro");

        jChbElzUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jChbElzUsuarios.setSelected(true);
        jChbElzUsuarios.setText("Usuarios");
        jChbElzUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuario.png"))); // NOI18N
        jChbElzUsuarios.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jChbElzUsuariosStateChanged(evt);
            }
        });
        jChbElzUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChbElzUsuariosActionPerformed(evt);
            }
        });
        jChbElzCadastro.add(jChbElzUsuarios);

        jChbElzClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jChbElzClientes.setSelected(true);
        jChbElzClientes.setText("Clientes");
        jChbElzClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cliente.png"))); // NOI18N
        jChbElzClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChbElzClientesActionPerformed(evt);
            }
        });
        jChbElzCadastro.add(jChbElzClientes);

        jChbElzFornecedo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jChbElzFornecedo.setSelected(true);
        jChbElzFornecedo.setText("Fornecedor");
        jChbElzFornecedo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fornecedor.jpg"))); // NOI18N
        jChbElzFornecedo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChbElzFornecedoActionPerformed(evt);
            }
        });
        jChbElzCadastro.add(jChbElzFornecedo);

        jChbElzProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jChbElzProdutos.setSelected(true);
        jChbElzProdutos.setText("Produtos");
        jChbElzProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produto.png"))); // NOI18N
        jChbElzProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChbElzProdutosActionPerformed(evt);
            }
        });
        jChbElzCadastro.add(jChbElzProdutos);

        jChbElzVendedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jChbElzVendedor.setSelected(true);
        jChbElzVendedor.setText("Vendedor");
        jChbElzVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vendedor.jpg"))); // NOI18N
        jChbElzVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChbElzVendedorActionPerformed(evt);
            }
        });
        jChbElzCadastro.add(jChbElzVendedor);
        jChbElzCadastro.add(jSeparator1);

        jChbElzSaie.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jChbElzSaie.setSelected(true);
        jChbElzSaie.setText("Sair");
        jChbElzSaie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/exit.png"))); // NOI18N
        jChbElzCadastro.add(jChbElzSaie);

        jMenuBar1.add(jChbElzCadastro);

        jMenu2.setText("Movimento");

        jCheckBoxMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jCheckBoxMenuItem4.setSelected(true);
        jCheckBoxMenuItem4.setText("Venda");
        jCheckBoxMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vendas.jpg"))); // NOI18N
        jMenu2.add(jCheckBoxMenuItem4);

        jChbElzVendaProduto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jChbElzVendaProduto.setSelected(true);
        jChbElzVendaProduto.setText("Venda_Produto");
        jChbElzVendaProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/venda_produto.jpg"))); // NOI18N
        jMenu2.add(jChbElzVendaProduto);

        jChbElzCompras.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        jChbElzCompras.setSelected(true);
        jChbElzCompras.setText("Compras");
        jChbElzCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/compra.jpg"))); // NOI18N
        jMenu2.add(jChbElzCompras);

        jChbElzComprasProduto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK));
        jChbElzComprasProduto.setSelected(true);
        jChbElzComprasProduto.setText("Compras_produto");
        jChbElzComprasProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/compra_produto.jpg"))); // NOI18N
        jMenu2.add(jChbElzComprasProduto);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 621, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jChbElzUsuariosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jChbElzUsuariosStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jChbElzUsuariosStateChanged

    private void jChbElzUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChbElzUsuariosActionPerformed
  JDlgElzUsuarios jDlgElzUsuarios = new JDlgElzUsuarios(null, true);
       jDlgElzUsuarios.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jChbElzUsuariosActionPerformed

    private void jChbElzClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChbElzClientesActionPerformed
       JDlgElzClientes jDlgElzClientes = new JDlgElzClientes(null, true);
       jDlgElzClientes.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jChbElzClientesActionPerformed

    private void jChbElzProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChbElzProdutosActionPerformed
       JDlgElzProduto jDlgElzProdutos = new JDlgElzProduto(null, true);
       jDlgElzProdutos.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jChbElzProdutosActionPerformed

    private void jChbElzFornecedoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChbElzFornecedoActionPerformed
       JDlgElzFornecedor jDlgElzFornecedor = new JDlgElzFornecedor(null, true);
       jDlgElzFornecedor.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jChbElzFornecedoActionPerformed

    private void jChbElzVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChbElzVendedorActionPerformed
       JDlgElzVendedor jDlgElzVendedores  = new JDlgElzVendedor (null, true);
       jDlgElzVendedores .setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jChbElzVendedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmElzPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmElzPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmElzPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmElzPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmElzPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jChbElzCadastro;
    private javax.swing.JCheckBoxMenuItem jChbElzClientes;
    private javax.swing.JCheckBoxMenuItem jChbElzCompras;
    private javax.swing.JCheckBoxMenuItem jChbElzComprasProduto;
    private javax.swing.JCheckBoxMenuItem jChbElzFornecedo;
    private javax.swing.JCheckBoxMenuItem jChbElzProdutos;
    private javax.swing.JCheckBoxMenuItem jChbElzSaie;
    private javax.swing.JCheckBoxMenuItem jChbElzUsuarios;
    private javax.swing.JCheckBoxMenuItem jChbElzVendaProduto;
    private javax.swing.JCheckBoxMenuItem jChbElzVendedor;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem4;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
